//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFnBlogServices.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nBlogMobileDB : DbContext
    {
        public nBlogMobileDB()
            : base("name=nBlogMobileDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<likes> likes { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
